spring.application.name=cp2

# Porta do servidor Tomcat
server.port=8080

# ============================================================
# Configuração Oracle Database FIAP
# Substitua SEU_RM pelo seu RM e SUA_SENHA pela senha FIAP
# ============================================================
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=SEU_RM_AQUI
spring.datasource.password=SUA_SENHA_AQUI

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON formatado (indentado)
spring.jackson.serialization.indent-output=true
